language: python

python:
  - "3.5"

sudo: false

env:
    global:
        - MOZ_HEADLESS=1
    matrix:
        - TOX_ENV=py27-django1.8
        - TOX_ENV=py27-django1.11
        - TOX_ENV=py35-django1.8
        - TOX_ENV=py35-django1.11
        - TOX_ENV=py35-django2.0
        - TOX_ENV=py36-django1.8
        - TOX_ENV=py36-django1.11
        - TOX_ENV=py36-django2.0
        - TOX_ENV=py37-django1.8
        - TOX_ENV=py37-django1.11
        - TOX_ENV=py37-django2.0

addons:
  firefox: latest

matrix:
    fast_finish: true


before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver


install:
    - pip install tox
    - pip install virtualenv

script:
    - tox -e $TOX_ENV
