language: python

python:
  - "3.5"

sudo: false

env:
    - TOX_ENV=py27-django1.8
    - TOX_ENV=py27-django1.11
    - TOX_ENV=py27-django2.0
    - TOX_ENV=py35-django1.8
    - TOX_ENV=py35-django1.11
    - TOX_ENV=py35-django2.0
    - TOX_ENV=py36-django1.8
    - TOX_ENV=py36-django1.11
    - TOX_ENV=py36-django2.0
    - TOX_ENV=py37-django1.8
    - TOX_ENV=py37-django1.11
    - TOX_ENV=py37-django2.0

matrix:
    fast_finish: true

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 6 # give xvfb some time to start

install:
    - pip install tox
    - pip install virtualenv

script:
    - tox -e $TOX_ENV
